logLevel: warning

healthCheckTimeout: 600

macros:
  server_base: >
    /app/llama-server
    --port ${PORT}
    --no-webui
    --no-mmap
    --prio 3
    --poll 100
  # --offline

models:
  nomic-embed-text-v2-moe:
    cmd: |
      ${server_base}
      --hf-repo nomic-ai/nomic-embed-text-v2-moe-GGUF:F16
      --embedding
      --ctx-size 512
      --batch-size 8192
      --ubatch-size 8192
      --n-gpu-layers 99
    ttl: 300
  gpt-oss-120b:
    cmd: |
      ${server_base}
      --hf-repo unsloth/gpt-oss-120b-GGUF:Q8_0
      --jinja
      --ctx-size 131072
      --n-predict 131072
      --n-gpu-layers 99
      --flash-attn on
      --temp 1.0
      --top-k 0
      --top-p 1.0
      --min-p 0.0
    # Note: Flash Attention not supported yet, causes segfault
    ttl: 300
  qwen3.5-122B-a10b:
    cmd: |
      ${server_base}
      --hf-repo unsloth/Qwen3.5-122B-A10B-GGUF:MXFP4_MOE
      --jinja
      --ctx-size 65536
      --n-predict 32768
      --n-gpu-layers 99
      --flash-attn on
      --temp 0.6
      --top-k 20
      --top-p 0.95
      --presence-penalty 0.0
      --repetition_penalty 1.0
      --min-p 0.0
    ttl: 300
  nemotron-3-super-120B-a12b:
    cmd: |
      ${server_base}
      --hf-repo unsloth/NVIDIA-Nemotron-3-Super-120B-A12B-GGUF:UD-IQ4_NL
      --jinja
      --ctx-size 65536
      --n-predict 32768
      --n-gpu-layers 99
      --flash-attn on
      --temp 0.6
      --top-p 0.95
    ttl: 300
  gemma-4-31b:
    cmd: |
      ${server_base}
      --hf-repo unsloth/gemma-4-31B-it-GGUF:UD-Q8_K_XL
      --jinja
      --ctx-size 262144
      --n-predict 32768
      --n-gpu-layers 99
      --flash-attn on
      --temp 1.0
      --top-p 0.95
      --top_k 64
    ttl: 300
  
groups:
  nomic-embed-text-v2-moe:
    persistent: true
    swap: false
    exclusive: false
    members:
      - nomic-embed-text-v2-moe
